language: php
php:
 - 5.3
 - 5.4
 - 5.5
 - 5.6

before_script:
 - composer install --prefer-source
 - mkdir -p builds/logs

script:
 - php vendor/bin/phpcs --standard=psr2 --encoding=utf-8 src/
 - php vendor/bin/phpunit --configuration phpunit.xml.travis tests

after_script:
 - php vendor/bin/coveralls -n
